#ifndef STAGE2UPGRADES_H
#define STAGE2UPGRADES_H

#include "bombScoutBot.h"
#include "hideScoutBot.h"
#include "jumpScoutBot.h"
#include "laserScoutBot.h"
#include "semiAutoScoutBot.h"
#include "thirtyShotScoutBot.h"
#include "bombTrackBot.h"
#include "hideTrackBot.h"
#include "jumpTrackBot.h"
#include "laserTrackBot.h"
#include "semiAutoTrackBot.h"
#include "thirtyShotTrackBot.h"
#include "hideBombBot.h"
#include "hideLaserBot.h"
#include "hideLongShotBot.h"
#include "hideSemiAutoBot.h"
#include "hideThirtyShotBot.h"
#include "jumpBombBot.h"
#include "jumpLaserBot.h"
#include "jumpLongShotBot.h"
#include "jumpSemiAutoBot.h"
#include "jumpThirtyShotBot.h"
#include "longShotScoutBot.h"
#include "longShotTrackBot.h"
#include "nukeHideBot.h"
#include "nukeJumpBot.h"
#include "nukeScoutBot.h"
#include "nukeTrackBot.h"

#endif  